# Generated by Django 4.1.4 on 2023-03-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(db_index=True, max_length=100, verbose_name="Назва практичної 'Практична робота №'")),
                ('title_practice', models.CharField(max_length=255, verbose_name='Мета роботи')),
                ('task', models.TextField(verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Практична роботу',
                'verbose_name_plural': 'Практичні роботи',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(db_index=True, max_length=100)),
                ('pract_var', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word.practice', verbose_name='Звязок з таблицею')),
            ],
            options={
                'verbose_name': 'Варіант',
                'verbose_name_plural': 'Варіанти робіт',
            },
        ),
        migrations.CreateModel(
            name='Photo_variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_variant_img', models.CharField(max_length=250, verbose_name='Практична N, Варіант N, (Завдання )')),
                ('variant_img', models.ImageField(upload_to='', verbose_name='Зображення завдання')),
                ('slug_img', models.SlugField(unique=True, verbose_name="URL за зразком 'practice-N-variant-N', де N номер варіанта та практичної")),
                ('img_connect_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word.variant', verbose_name='Звязок з таблицею')),
            ],
            options={
                'verbose_name': 'Фотографію',
                'verbose_name_plural': 'Фотографії варіантів',
            },
        ),
        migrations.CreateModel(
            name='Main_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.TextField(verbose_name='<b>Запитання</b><br>Інструкція для вирішення питання')),
                ('photo_word_cont', models.ImageField(upload_to='', verbose_name='Пояснююче зображення')),
                ('main_cont', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='word.practice', verbose_name='Звязок з таблицею')),
            ],
            options={
                'verbose_name': 'Вміст Практичної роботи',
                'verbose_name_plural': 'Вміст Практичних робіт',
            },
        ),
    ]
