# Generated by Django 4.1.4 on 2023-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_variant',
            name='name_variant_img',
            field=models.CharField(max_length=250, verbose_name='Практична N, Варіант N'),
        ),
    ]
