# Generated by Django 4.1.4 on 2023-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_photo_variant_name_variant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_variant',
            name='name_variant_img',
            field=models.CharField(max_length=250, unique=True, verbose_name='Практична N, Варіант N'),
        ),
    ]
