# Generated by Django 4.1.4 on 2023-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_photo_variant_name_variant_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='pract_var',
        ),
        migrations.AddField(
            model_name='variant',
            name='pract_var',
            field=models.ManyToManyField(to='word.practice', verbose_name='Звязок з таблицею'),
        ),
    ]
