# Generated by Django 4.1.4 on 2023-06-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_remove_variant_pract_var_variant_pract_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='control_questions',
            field=models.TextField(default=0, verbose_name='контрольні запитання'),
            preserve_default=False,
        ),
    ]
