# Generated by Django 4.1.4 on 2023-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_practice_control_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_variant',
            name='variant_img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Зображення завдання'),
        ),
    ]
