# Generated by Django 4.1.4 on 2023-03-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новину', 'verbose_name_plural': 'Новини'},
        ),
    ]
